# Assignment 3

name: Sean Deloddere <br>
studentnr: 914691

I opted not to solve Exercise 3.

#### imports

In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Exercise 1

### a) Identify most central and influential nodes

(nodes that have a higher value will be darker green, nodes with a lower value have a lighter colour.)

#### node degree

![Degree.PNG](Degree.png)
![Degree_table.PNG](Degree_table.png)

The degree of a node: the # of edges connected to that node. In our scenario an edge defines an interaction between people. This version is unweighed, so the length of the interaction doesn't matter. The nodes that have the highest degree aka the nodes with the most edges aka the people with the most interactions are seen in the table above.

#### Weighed degree

![W_Degree.PNG](W_Degree.png)
![W_Degree_table.PNG](W_Degree_table.png)

In contrast to degree, weighed degree takes into account the weight of the edge. The weighed degree of a node will be the sum of the weight of the edges of the node. In our scenario a long interaction will result in an edge with more weight. This means that the the nodes that score have the highest weight degree are the ones that correspond to the people that spent the most time interacting with others. Here it seems that 1437 and 1563 spent a lot of time interacting with each other, and this of course contributed to their total interaction duration. The 7 highest values are seen in the table above.

#### Closeness centrality

![Closeness.PNG](Closeness.png)
![Closeness_table.PNG](Closeness_table.png)

Closeness centrality shows how efficiently information is able to be spread through the graph through the node. It measures its average farness, through shortest path, to all other nodes. In our scenario this would mean if Bob interacted with Stacy, and Stacy interacted with Lisa, and Lisa and Bob did not interact directly with each other, their farness would be 2. If you do this with all other people and take the average you would get the closeness centrality. The nodes with the highest closeness centrality are displayed in the table above.

#### Betweenness centrality

![Betweeness.PNG](betweeness.png)
![Betweeness_table.PNG](betweeness_table.png)

Betweenness centrality quantifies the number of times a node acts as a bridge along the shortest path between two other nodes. So, if a node is part of a lot of shortest paths between nodes, it will have a high betweenness score. In our scenario this would usually be a person that links 2 groups together for example.1443 seems to be the main link between nodes on the upper left side and nodes on the right, explaining its high score.

Not every measure ranks the same nodes as most central, one could have a lot of very short interactions for example and rank high in degree but low in weighed degree. However, it is fairly clear that in this case, most of top nodes for one measure are also relatively high for the others. 1477 is top 7 for every measure, and 1443 scores really high for all of them, barely not making top 7 for weighed degree.

### b) Identify communities + c) Visualize communities

#### Modularity

Modularity measures the degree to which parts of a system can be decoupled into seperate communities that interact more among themselves than with the other communities. This method is depending on a resolution parameter, a higher value results in less clusters, a lower value in more clusters. With resolution set to 1, I get the graph that can be seen below. It seems like the groups are somewhat corresponding to the classes and the genders, with a few exceptions. Blue is mostly class 5A and female, purple mostly class 5A and male, althouth with a fair amount of female as well. Orange is mostly 5B and female, and green is 5B and male.

![Modularity.PNG](Modularity.png)

Another interesting case is what we get when we set the resolution to 2, in this case it finds a clear distinction between the classes. All nodes in the purple community are from class A, all the ones from the blue community are in class B. This tells us that the class attribute is the biggest tell for which community the node will be in.

![Modularity_2.PNG](Modularity_2.png)

#### Girvan-Newman

Girvan-Newman finds communities by progressively getting rid of more and more edges.The nodes that are still connected form communities. In the result below we can still somewhat see the 5A and 5B distinction, with their grey and purple colours. There are however a lot of additional 1-node communities, that are probably not that informative. 1430 also seems to be a weird outlier.

![G_N.PNG](G_N.png)

### d) Discuss communities and central nodes

![modularity_d.PNG](modularity_d.png)

We casn see that there are a lot of connections within the subclasses, especially the mostly female communty of class 5B is heavily interconnected, while in class 5A the 2 communties seem quite connected with each other. Looking at some central nodes, 1437 for example, the node that scored the heighest on the weighed degree, seems to be a link from orange (F-5B) to both  purple (mostly M-5A) and green (M-5B). Another interesting node is 1457, it seems like that is a girl from 5A that interacts quite a lot with other girls from 5B, but within her own class seems to interact more with the boys, hence her being in the more male dominated communty of 5A. Those different connections are also reflected in this node scoring high on the weighted degree list. 1443, a node with a high betweenness score, seems to quickly be the only link between blue(F-5A) and orange(F-5B) when increasing the treshold for the edges, so it is clear why its betweenness score is so high. Not all central nodes are bridge nodes though. An example of a central node that isn't a bridge node is node 1452. It scores 5th on the weighed degree list, but isn't connected strongly with any nodes outside of its community. However, the high score still makes sense since the node is so heavily connected within the community. One could conclude that some central nodes are bridges to other communities, while other central nodes are the main node within a community that connects to others within the community.

## Exercise 2

### a) Propose a greedy algorithm to find a subgraph with good density according to this definition.

The greedy algorithm I propose is to start off with the full graph and then iteratively drop the nodes with the lowest weighed degree and calculate the density of the remaining graph. The reason for dropping the node with the lowest weighed degree is that this will decrease the numerator the least out of dropping any other node, while the denominator will decrease the same regardless of what node is dropped. We can either continue dropping nodes untill no nodes are left, and then look at whichever subgraph had the highest density, or we can be extra greedy and stop straight away when we notice the density is no longer improving.

### b) Evaluate the results on the dolphins.txt data set

In [314]:
def calculate_density(S,edges_dict):
    nom = 0
    if(len(edges_dict)==0):
        return nom
    for i in edges_dict.keys():
        nom += len(edges_dict[i])
    density = nom/S   
    return density

Calculates the density based on the formula provided.

In [315]:
def prune_lowest(lowest_degree):
    pruned=[]
    for i in degrees.keys(): 
        if(degrees[i]==lowest_degree):
            pruned.append(i)
    for k in pruned:
        for j in edges_dict[k]:
            (edges_dict[j]).remove(k)
            degrees[j]=degrees[j]-1
             
        del edges_dict[k]
        del degrees[k]

Prunes the node from the graph. It is deleted from the dictionaries that contain the degrees and the edges of all nodes, and its edges with other nodes are also removed from those nodes collections. Those nodes degrees are also lowered.

In [316]:
edges_temp = []
degrees={}
edges_dict={}
edges = []
file = open("dolphins.txt","r")
lines = file.readlines()
num_nodes = int(lines[0])
edges_temp = lines[1:]
for i in edges_temp:
    edge = list(map(int,i.split()))
    edges.append(edge)
    if edge[0] not in edges_dict.keys():
        degrees[edge[0]]=0
        edges_dict[edge[0]]=[]
    degrees[edge[0]]+=1
    edges_dict[edge[0]].append(edge[1])

    if edge[1] not in edges_dict.keys():
        degrees[edge[1]]=0
        edges_dict[edge[1]]=[]
    degrees[edge[1]]+=1
    edges_dict[edge[1]].append(edge[0])
file.close()
#print(edges_dict)
#print(degrees)


maximum_density = 0
subgraph = []
while(len(degrees)>0):
    lowest_degree = 50000000000
    
    #look for node with lowest degree and prune it
    for i in degrees.keys():
        lowest_degree = min(degrees[i],lowest_degree)
    prune_lowest(lowest_degree)
    
     #check if density after pruning went up, if so, store new density in place of old one as the max density.
    if(calculate_density(len(degrees),edges_dict)>maximum_density):
        maximum_density = calculate_density(len(degrees),edges_dict)
        print("maximum density: "+str(maximum_density)+", with subgraph:")
        subgraph = edges_dict.keys()
        print(subgraph)

maximum density: 5.660377358490566, with subgraph:
dict_keys([11, 1, 15, 16, 41, 43, 48, 18, 2, 20, 27, 28, 29, 37, 42, 55, 3, 45, 62, 9, 4, 60, 52, 10, 6, 14, 57, 58, 7, 8, 31, 21, 38, 46, 33, 30, 34, 17, 25, 35, 39, 44, 51, 53, 19, 56, 26, 22, 24, 50, 40, 47, 54])
maximum density: 5.956521739130435, with subgraph:
dict_keys([11, 1, 15, 16, 41, 43, 48, 18, 2, 20, 27, 28, 29, 37, 42, 55, 3, 45, 62, 9, 4, 60, 52, 10, 6, 14, 58, 7, 8, 31, 21, 38, 46, 30, 34, 17, 25, 35, 39, 44, 51, 53, 19, 26, 22, 24])
maximum density: 6.0, with subgraph:
dict_keys([11, 1, 15, 16, 41, 43, 48, 18, 2, 20, 27, 28, 29, 37, 42, 55, 3, 45, 9, 4, 60, 52, 10, 6, 14, 58, 7, 8, 31, 21, 38, 46, 30, 34, 17, 25, 35, 39, 44, 51, 53, 19, 26, 22, 24])
maximum density: 6.051282051282051, with subgraph:
dict_keys([11, 1, 15, 16, 41, 43, 48, 18, 2, 20, 28, 29, 37, 42, 55, 45, 9, 60, 52, 10, 14, 58, 7, 8, 31, 21, 38, 46, 30, 34, 17, 25, 35, 39, 44, 51, 53, 19, 22])
maximum density: 6.054054054054054, with subgraph:
dict_key

Basically done in code what I explained in words in a). The resulting subgraph and its density are the last line printed above. I couldn't figure out how to only print the last line, since it didn't want to print outside of the for loops, excuse me for the inconvenience.

## Exercise 3

I opted not to solve exercise 3.

## Exercise 4

In [128]:
train_data = pd.read_csv('jester-800-10.csv', index_col = 0, usecols=[1,2,3,4,5,6,7,8,9,10,11])
test_data = pd.read_csv('jester-800-10.csv', index_col = 0, usecols=[1,2,3,4,5,6,7,8,9,10,11])
train_data.head()

joke_5  joke_7  joke_8  joke_13  joke_15  joke_16  joke_17  \
user_id                                                                  
user_5013        0       1       0        0        1        0        0   
user_10016       0       0       0        1        0        1        1   
user_21844       1       1       1        1        1        1        1   
user_3403        1       0       0        1        0        1        1   
user_23240       0       1       0        1        1        1        1   

            joke_18  joke_19  joke_20  
user_id                                
user_5013         1        1        1  
user_10016        1        0        1  
user_21844        1        1        1  
user_3403         0        1        1  
user_23240        1        0        1

In [129]:
train_data_t = train_data.T
Transition_df = pd.concat([train_data,train_data_t],axis=0).fillna(0)
connection_matrix = Transition_df.to_numpy()
Transition_df.head()

joke_5  joke_7  joke_8  joke_13  joke_15  joke_16  joke_17  \
user_5013      0.0     1.0     0.0      0.0      1.0      0.0      0.0   
user_10016     0.0     0.0     0.0      1.0      0.0      1.0      1.0   
user_21844     1.0     1.0     1.0      1.0      1.0      1.0      1.0   
user_3403      1.0     0.0     0.0      1.0      0.0      1.0      1.0   
user_23240     0.0     1.0     0.0      1.0      1.0      1.0      1.0   

            joke_18  joke_19  joke_20  ...  user_4442  user_15882  user_10237  \
user_5013       1.0      1.0      1.0  ...        0.0         0.0         0.0   
user_10016      1.0      0.0      1.0  ...        0.0         0.0         0.0   
user_21844      1.0      1.0      1.0  ...        0.0         0.0         0.0   
user_3403       0.0      1.0      1.0  ...        0.0         0.0         0.0   
user_23240      1.0      0.0      1.0  ...        0.0         0.0         0.0   

            user_16014  user_12180  user_7471  user_22586  user_14652  \
user_5013          0.0         0.0        0.0         0.0         0.0   
user_10016         0.0         0.0        0.0         0.0         0.0   
user_21844         0.0         0.0        0.0         0.0         0.0   
user_3403          0.0         0.0        0.0         0.0         0.0   
user_23240         0.0         0.0        0.0         0.0         0.0   

            user_15506  user_5338  
user_5013          0.0        0.0  
user_10016         0.0        0.0  
user_21844         0.0        0.0  
user_3403          0.0        0.0  
user_23240         0.0        0.0  

[5 rows x 810 columns]

I transpose the matrix and add it to the original matrix so that I not only have transitions from users to jokes, but also from jokes to users. Direct transitions between users and between jokes are obviously set to 0, since they are impossible.

#### K most similar users

In [130]:
neighbours_list = []
for i in range(len(connection_matrix)):
    neighbours = []
    for j in range(len(connection_matrix[i])):
        if connection_matrix[i][j]>0:
            neighbours.append(j)
    neighbours_list.append(neighbours)

I precomputed all the neighbouring nodes for each node to save runtime during the SimRank algorithm

In [131]:
def SimRank(i,j,k):
    if(i==j):
        return 1
    else:    
        if(len(neighbours_list[i]) == 0 or len(neighbours_list[j]) == 0 or k >= 2):
            return 0
        else:
            x = C/(len(neighbours_list[i])*len(neighbours_list[j]))
            sr = 0
            for p in neighbours_list[i]:
                for q in neighbours_list[j]:
                    sr += x * SimRank(p,q,k+1)
            return sr

This is a very dense graph with a lot of edges (jokes have hundreds of edges), without a limit it can take very long to run. So, in order to lower computation time, I added a k to the algorithm. This k will make it so that when the algorithm goes too deep recursively, it will return 0. This shouldn't be too harmful to the outcome, because if it takes too many steps to get to another node, it isn't a very close node anyway (at least in this particular graph) 

In [133]:
C = 0.8
SimRanks = np.zeros((800,800))
for i in range(len(connection_matrix)-10):
    for j in range(len(connection_matrix)-10):
        SimRanks[i][j] = SimRank(i,j,0)
    if(i%40 == 39):
        print(str(np.round(((i+1)/8.1),1))+"% done")

4.9% done
9.9% done
14.8% done
19.8% done
24.7% done
29.6% done
34.6% done
39.5% done
44.4% done
49.4% done
54.3% done
59.3% done
64.2% done
69.1% done
74.1% done
79.0% done
84.0% done
88.9% done
93.8% done
98.8% done


SimRanks now contains the similarity of each user to every other user. Next we sort every row based on this value:

In [134]:
SimRanks_sorted = np.argsort(SimRanks, axis = 1)[:,::-1]
print(SimRanks_sorted)

[[  0 358 545 ... 242  52 239]
 [  1 110 444 ... 230 727 629]
 [  2 545 358 ... 630  52 239]
 ...
 [797 545 358 ... 540 162 554]
 [798 255 159 ... 474 691 638]
 [799 575 691 ... 434 666 261]]


The first column (column 0) is always the user itself, which makes sense, every user is the most similar to itself. So when we want the K (=20) most similar users, we take column 1 to 20.

In [135]:
k_most_sim = SimRanks_sorted[:,1:20]
print(k_most_sim)

[[358 545 537 ... 198 312 325]
 [110 444  14 ... 520 590  92]
 [545 358   0 ... 161 234 307]
 ...
 [545 358 548 ...  55 204 205]
 [255 159 734 ... 548 482 345]
 [575 691  27 ... 226 103  24]]


Now we have the 20 most similar users for each user, so we have completed the first phase. Let's check a few examples to see whether the users are indeed similar:

In [144]:
joke_scores = train_data.to_numpy()
print(joke_scores[0])
for i in k_most_sim[0][0:5]:
    print(joke_scores[i])

[0 1 0 0 1 0 0 1 1 1]
[0 1 0 0 1 0 0 1 0 1]
[0 1 0 0 1 0 0 1 0 1]
[0 1 0 0 1 0 0 1 1 1]
[0 1 0 1 1 0 0 1 1 1]
[0 1 0 1 1 0 0 1 1 1]


It seems like the most similar users differ from each other by at most 1 joke, so looks like the algorithm worked!

#### Recommend jokes

Now that we have the 20 most similar users for each user, we can look within this group to find the best joke to recommend to each user. The way I will approach this is going over every user in the similar user list and looking at the scores they gave to jokes. For every user that gave a positive review to a joke, I increase that jokes score by 1. At the end, I have a score of how the users as a group liked every joke:

In [151]:
def cummulative_joke_score(most_sim):
    cumul_joke_scores = [0,0,0,0,0,0,0,0,0,0]
    for user in most_sim:
        for i in range(len(joke_scores[user])):
            cumul_joke_scores[i] += joke_scores[user][i]
    return cumul_joke_scores        

Next up I can use this score to recommend a joke to every user. I use argsort to get the jokes that received the highest scores from the group, and then I go from best joke to worst joke untill I find one that the user has not reviewed yet. As soon as I find one I stop and recommend that joke. If the user has already reviewed all jokes, I just return that I can't recommend anything else.

In [203]:
def recommend_joke(own_joke_scores, cumul_joke_scores):
    joke_scores_sorted = np.argsort(cumul_joke_scores, axis = 0)[::-1]
    for i in joke_scores_sorted:
        if(own_joke_scores[i] == 0):
            return train_data.columns[i]
    return "nothing, you already reviewed all jokes"

Here is a demonstration of the recommendations for all the users in the training set:

In [204]:
recommendations = []
for i in range(800):
    c_joke_score = cummulative_joke_score(k_most_sim[i])
    recommendation = recommend_joke(joke_scores[i],c_joke_score)
    recommendations.append(recommendation)

In [206]:
for i in range(10):
    print("For user: "+str(train_data.index[i])+", I recommend "+str(recommendations[i])+".")

For user: user_5013, I recommend joke_13.
For user: user_10016, I recommend joke_7.
For user: user_21844, I recommend nothing, you already reviewed all jokes.
For user: user_3403, I recommend joke_18.
For user: user_23240, I recommend joke_19.
For user: user_835, I recommend nothing, you already reviewed all jokes.
For user: user_1538, I recommend joke_18.
For user: user_7229, I recommend joke_17.
For user: user_10809, I recommend joke_19.
For user: user_14356, I recommend joke_17.


If I want to now recommend a joke to a completely new person, e.g. from the test set: 

In [217]:
test_matrix = test_data.to_numpy()
new_user_scores = test_matrix[0]
print(new_user_scores)

[0 1 0 0 1 0 0 1 1 1]


I can first check whether I have the same scores already in the training set, and if so, just give the same recommendations:

In [222]:
train_matrix = train_data.to_numpy()
for i in range(len(train_matrix)):
    if new_user_scores.all() == train_matrix[i].all():
        c_joke_score = cummulative_joke_score(k_most_sim[i])
        recommendation = recommend_joke(joke_scores[i],c_joke_score)
        break
print("For this new user, I recommend "+str(recommendation))

For this new user, I recommend joke_13


This new user is actually identical to the first user in the train data, so it makes sense that they get the same suggestion!

If the test person is not yet in the training set, I can go over the steps again of finding its most similar users, summing up their scores and recommending the best joke that the user has not reviewed yet.

## Exercise 5

### a) Modify code so that features are based on frequency of words. Compare accuracy with and without preprocessing.

#### Imports

In [223]:
import nltk
import random
from nltk.corpus import movie_reviews

#### Download the movie reviews

In [224]:
#nltk.download('movie_reviews')

#### Construct list of documents labeled with the appropriate categories

In [225]:
documents = [(list(movie_reviews.words(fileid)), category)
              for category in movie_reviews.categories()
              for fileid in movie_reviews.fileids(category)]
random.shuffle(documents)

#### Feature Extractors

In [226]:
all_words = nltk.FreqDist(w.lower() for w in movie_reviews.words())
word_features = list(all_words)[:2000]

##### Throughout the notebook I will refer to the classifiers using these features as "contain" classifiers:

In [227]:
def document_features_contained(document):
    document_words = set(document)
    features = {}
    for word in word_features:
        features['contains({})'.format(word)] = (word in document_words)
    return features

I cast document to a set because it is much faster to look if an element occurs in a set than in a list.

##### Throughout the notebook I will refer to the classifiers using these features as "frequency" classifiers:

In [228]:
def document_features_frequencies(document):
    features = {}
    for word in word_features:
        features[word] = 0
    for word_ in document:
        if word_ in word_features:
            features[word_] += 1
    return features

When we want to look at how frequently a word occurs in the document, we can not cast it to a set, because then dupplicates are lost.

### Without preprocessing

#### Train classifiers

In [229]:
featuresets = [(document_features_contained(d), c) for (d,c) in documents]
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_c = nltk.NaiveBayesClassifier.train(train_set)
print("Accuracy of classifier that looks only at whether a word occurs or not in a document: "+str(nltk.classify.accuracy(classifier_c, test_set))+"\n") 
#classifier_c.show_most_informative_features(35)

Accuracy of classifier that looks only at whether a word occurs or not in a document: 0.81



In [230]:
featuresets = [(document_features_frequencies(d), c) for (d,c) in documents]
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_f = nltk.NaiveBayesClassifier.train(train_set)
print("Accuracy of classifier looks at how frequently a word occurs in a document: "+str(nltk.classify.accuracy(classifier_f, test_set))+"\n") 
#classifier_f.show_most_informative_features(35)

Accuracy of classifier looks at how frequently a word occurs in a document: 0.72



Note: These accuracies are not always the same due to the shuffling of the documents so that different documents are in the training and testing set. I am discussing results I saw most frequently.

It seems that without doing any preprocessing, taking into account the frequency (amount of occurences) of words in the documents, as the frequency classifier does, does not improve the accuracy, in fact, most of the time it makes it worse. One of the reasons for this decrease in accuracy could be that the frequency classifier takes words into account that occur a lot, but aren't really that informative. More about that in the motivation of why to remove stopwords. 

### With preprocessing

#### Stopword removal

Motivation: When we look at the 35 most informative features, we see that the ones for the contains classifier make a lot of sense, while in the ones for frequency classifier, there are words like 'who', 'and', 'is', 'of', 'to', that, to a human, don't really look they are informative on wether or not a review will be possible or not. These are all common stopwords, so I hypothesize that the frequency classifier performs better after removing these words.

#### Imports

In [231]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

#### Download stopwords

In [232]:
#nltk.download('stopwords')

We can see that the documents are already tokenized:

In [233]:
print(documents[1][0][0:20])

['capsule', ':', 'the', 'world', 'will', 'come', 'to', 'an', 'end', 'at', 'midnight', '.', 'everyone', 'knows', 'it', 'and', 'must', 'make', 'a', 'final']


So, we can move on straight to stop word removal.

#### Remove stopwords

In [234]:
stop_words = set(stopwords.words('english'))

filtered_documents = []
for document in documents:
    filtered_document = [token for token in document[0] if token not in stop_words]
    filtered_documents.append([filtered_document, document[1]])

print("with stopwords: ")
print(documents[0][0][:20])
print("\nwithout stopwords: ")
print(filtered_documents[0][0][:20])

with stopwords: 
['starring', 'ben', 'stiller', ',', 'elizabeth', 'hurley', ',', 'maria', 'bello', ',', 'janeane', 'garofalo', 'screenplay', 'by', 'david', 'veloz', ',', 'based', 'on', 'the']

without stopwords: 
['starring', 'ben', 'stiller', ',', 'elizabeth', 'hurley', ',', 'maria', 'bello', ',', 'janeane', 'garofalo', 'screenplay', 'david', 'veloz', ',', 'based', 'novel', 'jerry', 'stahl']


#### Train and test again:

In [235]:
featuresets = [(document_features_contained(d), c) for (d,c) in filtered_documents]
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_c = nltk.NaiveBayesClassifier.train(train_set)
print("Accuracy of classifier that looks only at whether a word occurs or not in a document: "+str(nltk.classify.accuracy(classifier_c, test_set))+"\n") 
#classifier_c.show_most_informative_features(35)

Accuracy of classifier that looks only at whether a word occurs or not in a document: 0.78



In [236]:
featuresets = [(document_features_frequencies(d), c) for (d,c) in filtered_documents]
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_f = nltk.NaiveBayesClassifier.train(train_set)
print("Accuracy of classifier looks at how frequently a word occurs in a document: "+str(nltk.classify.accuracy(classifier_f, test_set))+"\n") 
#classifier_f.show_most_informative_features(35)

Accuracy of classifier looks at how frequently a word occurs in a document: 0.77



We can see that while the accuracy for the contains classifier sometimes decreases, the accuracy for the frequency classifier almost always improves, as I hypothesized. Another thing to notice is that 4 is now a word in the most informative words of the frequency classifier, so it is likely that removing numbers could have a positive effect on the accuracy as well.

### b) Augment the movie review document to use hypernyms

#### imports

In [106]:
from nltk.corpus import wordnet as wn
import copy

#### Download wordnet

In [107]:
#nltk.download('wordnet')

#### Replacing words in documents by hypernyms

In [207]:
hypernyms_documents = []
for (d,c) in filtered_documents:
    hypernyms_document = []
    for word in d:
        synset = wn.synsets(word)
        #if not empty:
        if(synset):
            hypernym = synset[0].hypernyms()
            #if not empty:
            if(hypernym):
                lemma = hypernym[0].lemma_names()
                #if not empty
                if(lemma):
                    lemma_l = lemma[0].lower()
                    hypernyms_document.append(lemma_l)
    hypernyms_documents.append((hypernyms_document, c))

#### Replacing most frequent words by hypernyms

In [208]:
word_features_only_hypernyms = []
for word in word_features:
    synset = wn.synsets(word)
    #if not empty:
    if(synset):
        hypernym = synset[0].hypernyms()
        #if not empty:
        if(hypernym):
            lemma = hypernym[0].lemma_names()
            #if not empty:
            if(lemma):
                lemma_l = lemma[0].lower()
                word_features_only_hypernyms.append(lemma_l)

##### Assumption made: the first synset, hypernym and lemma are the most representative

I made this assumption mainly to save computing time, because it take incredible long to run while incorporating all the synsets and hypernyms. A more nuanced implementation could of course result in a higher eventual accuracy.

#### slightly adapting feature functions to take into account the different frequent words

In [110]:
def document_features_contained_2(document,word_f):
    document_words = set(document)
    features = {}
    for word in word_f:
        features['contains({})'.format(word)] = (word in document_words)
    return features

In [111]:
def document_features_frequencies_2(document,word_f):
    features = {}
    for word in word_f:
        features[word] = 0
    for word_ in document:
        if word_ in word_f:
            features[word_] += 1
    return features

#### Train + test contain classifier using only hypernyms

In [122]:
featuresets = []
i=0
for (d,c) in hypernyms_documents:
    featuresets.append((document_features_contained_2(d,word_features_only_hypernyms), c))
    if(i%10 == 9):
        print(str((i+1)/20)+"% done.")
    i += 1
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_c_oh = nltk.NaiveBayesClassifier.train(train_set)

0.5% done.
1.0% done.
1.5% done.
2.0% done.
2.5% done.
3.0% done.
3.5% done.
4.0% done.
4.5% done.
5.0% done.
5.5% done.
6.0% done.
6.5% done.
7.0% done.
7.5% done.
8.0% done.
8.5% done.
9.0% done.
9.5% done.
10.0% done.
10.5% done.
11.0% done.
11.5% done.
12.0% done.
12.5% done.
13.0% done.
13.5% done.
14.0% done.
14.5% done.
15.0% done.
15.5% done.
16.0% done.
16.5% done.
17.0% done.
17.5% done.
18.0% done.
18.5% done.
19.0% done.
19.5% done.
20.0% done.
20.5% done.
21.0% done.
21.5% done.
22.0% done.
22.5% done.
23.0% done.
23.5% done.
24.0% done.
24.5% done.
25.0% done.
25.5% done.
26.0% done.
26.5% done.
27.0% done.
27.5% done.
28.0% done.
28.5% done.
29.0% done.
29.5% done.
30.0% done.
30.5% done.
31.0% done.
31.5% done.
32.0% done.
32.5% done.
33.0% done.
33.5% done.
34.0% done.
34.5% done.
35.0% done.
35.5% done.
36.0% done.
36.5% done.
37.0% done.
37.5% done.
38.0% done.
38.5% done.
39.0% done.
39.5% done.
40.0% done.
40.5% done.
41.0% done.
41.5% done.
42.0% done.
42.5% done.

In [123]:
print("Accuracy of contains classifier with only hypernyms: "+str(nltk.classify.accuracy(classifier_c_oh, test_set))+"\n") 
classifier_c_oh.show_most_informative_features(5)

Accuracy of contains classifier with only hypernyms: 0.66

Most Informative Features
  contains(word_picture) = True              pos : neg    =      3.5 : 1.0
contains(disorderliness) = True              neg : pos    =      3.3 : 1.0
     contains(simpleton) = True              neg : pos    =      3.1 : 1.0
     contains(gentleman) = True              neg : pos    =      2.9 : 1.0
       contains(diapsid) = True              neg : pos    =      2.8 : 1.0


#### Train + test frequency classifier using only hypernyms

In [124]:
featuresets = []
i=0
for (d,c) in hypernyms_documents:
    featuresets.append((document_features_frequencies_2(d,word_features_only_hypernyms), c))
    if(i%10 == 9):
        print(str((i+1)/20)+"% done.")
    i += 1
train_set, test_set = featuresets[100:], featuresets[:100]
classifier_f_oh = nltk.NaiveBayesClassifier.train(train_set)

0.5% done.
1.0% done.
1.5% done.
2.0% done.
2.5% done.
3.0% done.
3.5% done.
4.0% done.
4.5% done.
5.0% done.
5.5% done.
6.0% done.
6.5% done.
7.0% done.
7.5% done.
8.0% done.
8.5% done.
9.0% done.
9.5% done.
10.0% done.
10.5% done.
11.0% done.
11.5% done.
12.0% done.
12.5% done.
13.0% done.
13.5% done.
14.0% done.
14.5% done.
15.0% done.
15.5% done.
16.0% done.
16.5% done.
17.0% done.
17.5% done.
18.0% done.
18.5% done.
19.0% done.
19.5% done.
20.0% done.
20.5% done.
21.0% done.
21.5% done.
22.0% done.
22.5% done.
23.0% done.
23.5% done.
24.0% done.
24.5% done.
25.0% done.
25.5% done.
26.0% done.
26.5% done.
27.0% done.
27.5% done.
28.0% done.
28.5% done.
29.0% done.
29.5% done.
30.0% done.
30.5% done.
31.0% done.
31.5% done.
32.0% done.
32.5% done.
33.0% done.
33.5% done.
34.0% done.
34.5% done.
35.0% done.
35.5% done.
36.0% done.
36.5% done.
37.0% done.
37.5% done.
38.0% done.
38.5% done.
39.0% done.
39.5% done.
40.0% done.
40.5% done.
41.0% done.
41.5% done.
42.0% done.
42.5% done.

In [210]:
print("Accuracy of frequency classifier with only hypernyms: "+str(nltk.classify.accuracy(classifier_f_oh, test_set))+"\n") 
classifier_f_oh.show_most_informative_features(5)

Accuracy of frequency classifier with only hypernyms: 0.65

Most Informative Features
                   being = 7                 pos : neg    =      9.3 : 1.0
               simpleton = 3                 neg : pos    =      9.1 : 1.0
                    kind = 12                neg : pos    =      8.1 : 1.0
                 society = 2                 pos : neg    =      7.9 : 1.0
             orientation = 3                 pos : neg    =      7.2 : 1.0


It seems that both the classifiers perform worse when using the hypernyms over the actual words. The frequency classifier seems to even have 'kind = 12' as a feature that indicates negative sentiment, which seems very strange. However, this could also be because a hyponym (the inverse of hypernym) of 'kind' is used frequently with a 'not' before it, but since 'not' is a stopword and we drop it, this meaning gets lost. This doesn't mean that the use of hypernyms is bad, this was a pretty brute force, not nuanced way of implementing hypernyms. Replacing words with their hypernym might make them more general, but it also loses parts of their meaning. I highly suspect that replacing only the less frequent words, that actually have something to gain from being more general, by their hypernyms, would result in a better accuracy. On top of that, I also made the assumption mentioned above. Including all synsets and hypernyms could also hurt the accuracy, but perhaps there is a better way of choosing which ones to use that could improve the accuracy.